In [69]:
import numpy as np
import pandas as pd  
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score, accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
data = pd.read_csv(r"C:\Users\Dell\Desktop\Uv Techno\Machine Learning\Project\IBM_Employee_Data.csv")

In [3]:
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [5]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [8]:

data = data.drop(['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours'], axis=1)

In [9]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='str')

In [10]:
data.shape

(1470, 31)

#encoding categorical feature

In [12]:
data.dtypes

Age                         int64
Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [13]:
data['Attrition'] = data['Attrition'].map({'Yes':1, 'No':0})
data['OverTime'] = data['OverTime'].map({'Yes':1, 'No':0})

In [15]:
# Label Encoding

le = LabelEncoder()

data['Gender'] = le.fit_transform(data['Gender'])
data['BusinessTravel'] = le.fit_transform(data['BusinessTravel'])
data['MaritalStatus'] = le.fit_transform(data['MaritalStatus'])

In [16]:
data.head(3)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,2,1102,Sales,1,2,Life Sciences,2,0,...,3,1,0,8,0,1,6,4,0,5
1,49,0,1,279,Research & Development,8,1,Life Sciences,3,1,...,4,4,1,10,3,3,10,7,1,7
2,37,1,2,1373,Research & Development,2,2,Other,4,1,...,3,2,0,7,3,3,0,0,0,0

In [17]:
# One-Hot Encoding : It prevents dummy variable trap and reduces extra columns with many categories like: Department, JobRole, EducationField

data = pd.get_dummies(data, columns=['Department', 'JobRole','EducationField'], drop_first=True)

In [18]:
data.head(3)

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree
0,41,1,2,1102,1,2,2,0,94,3,...,False,False,False,True,False,True,False,False,False,False
1,49,0,1,279,8,1,3,1,61,2,...,False,False,True,False,False,True,False,False,False,False
2,37,1,2,1373,2,2,4,1,92,2,...,False,False,False,False,False,False,False,False,True,False

In [21]:
data = data.astype(int)

In [22]:
data.head(3)

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree
0,41,1,2,1102,1,2,2,0,94,3,...,0,0,0,1,0,1,0,0,0,0
1,49,0,1,279,8,1,3,1,61,2,...,0,0,1,0,0,1,0,0,0,0
2,37,1,2,1373,2,2,4,1,92,2,...,0,0,0,0,0,0,0,0,1,0

In [23]:
data.shape

(1470, 43)

Defining X and Y

In [54]:
X = data.drop(['MonthlyIncome','Attrition'],axis = 1)
Y = data['MonthlyIncome']

Train Test Split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

Model Building

In [56]:
rf_model = RandomForestRegressor(random_state=42)

In [57]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [58]:
y_pred_rf = rf_model.predict(X_test)

In [59]:
r2_score(y_test, y_pred_rf)

0.9439345413536866

In [60]:
mean_absolute_error(y_test, y_pred_rf)

821.6299659863946

In [52]:
print(X_train.columns)

Index(['Age', 'BusinessTravel', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Department_Research & Development',
       'Department_Sales', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'EducationField_Life Sciences',
       'EducationField_Marketing', 'EducationField_Medical',
       'EducationField_Other', 'EducationField_Technical Degree'],
      dtype='str')

Attrition Prediction

In [71]:
X_attrition = data.drop(['Attrition'], axis=1)
Y_attrition = data['Attrition']

In [72]:
X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(
    X_attrition, Y_attrition, test_size =0.2, random_state =42
)

In [73]:
classification = RandomForestClassifier(random_state=42)

In [74]:
classification.fit(X_train_a, y_train_a)

RandomForestClassifier(random_state=42)

In [75]:
y_pred_attrition = classification.predict(X_test_a)

In [76]:
accuracy_score(y_test_a, y_pred_attrition)

0.8775510204081632

Deployement

In [77]:
import joblib

joblib.dump(rf_model, "salary_model.pkl")
joblib.dump(classification, "attrition_model.pkl")

['attrition_model.pkl']

In [ ]:
#Verify Saved Files
import os
os.listdir()

['072586267e',
 'attrition_model.pkl',
 'bin',
 'Code.exe',
 'Code.VisualElementsManifest.xml',
 'salary_model.pkl',
 'unins000.dat',
 'unins000.exe',
 'unins000.msg']

In [ ]:
#Test loading of models

salary_model = joblib.load("salary_model.pkl")
attrition_model = joblib.load("attrition_model.pkl")